name: pre-deploy-check
run-name: Pre-deploy checks for AFL tracker backend by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      image_uri:
        description: 'Docker image URI to use in Pulumi preview'
        required: true
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      
jobs:
    pre-deploy-check:
      runs-on: ubuntu-latest
      environment: dev
      permissions:
        contents: read
        id-token: write

      steps:
        - name: Debug Variables
          run: |
            echo "Provider: ${{ vars.GCP_WIF_PROVIDER }}"
            echo "Account: ${{ vars.GCP_APP_DEPLOYER_SERVICE_ACCOUNT }}"
            echo "Azure Client ID: ${{ vars.AZURE_CLIENT_ID }}"
            echo "Azure Tenant ID: ${{ vars.AZURE_TENANT_ID }}"
            echo "Azure Subscription ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"

        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Setup jdk 21 for Pre-deploy Check
          uses: actions/setup-java@v4
          with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'
        
        - name: Authenticate to Google Cloud
          id: gcloud-auth
          uses: google-github-actions/auth@v2
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
            service_account: ${{ vars.GCP_APP_DEPLOYER_SERVICE_ACCOUNT }}

        - name: Authenticate to Azure
          id: azure-login
          uses: azure/login@v1
          with:
            client-id: ${{ vars.AZURE_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID }}
            subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

        - name: Copy Maven settings.xml
          working-directory: ./pulumi-infra
          run: |
            mkdir -p ~/.m2
            cp settings.xml ~/.m2/settings.xml

        - name: Pulumi Pre-Deploy Check (Preview)
          uses: pulumi/actions@v6
          with:
              command: preview
              stack-name: dev
              work-dir: ./pulumi-infra
          env:
              PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
              GCP_ACCESS_TOKEN: ${{ steps.gcloud-auth.outputs.access_token }}
              ARM_USE_OIDC: true
              ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
              ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
              ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
              ARM_OIDC_TOKEN: ${{ steps.azure-login.outputs.token }}
              PULUMI_CONFIG_PASSTHROUGH: | 
                gcp:project=${{ vars.GCP_PROJECT_ID }},\
                gcp:region=${{ vars.GCP_REGION }},\
                azure-native:subscriptionId=${{ vars.AZURE_SUBSCRIPTION_ID }},\
                azure-native:location=${{ vars.AZURE_LOCATION }},\
                app-image=${{ inputs.image_uri }}