name: pre-deploy-check
run-name: Pre-deploy checks for AFL tracker backend by @${{ github.actor }}
on:
  workflow_call:
    inputs:
      image_uri:
        description: 'Docker image URI to use in Pulumi preview'
        required: true
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      
jobs:
    pre-deploy-check:
      runs-on: ubuntu-latest
      environment: dev
      permissions:
        contents: read
        id-token: write

      steps:
        - name: Debug Variables
          run: |
            echo "Provider: ${{ vars.WIF_PROVIDER }}"
            echo "Account: ${{ vars.APP_DEPLOYER_SERVICE_ACCOUNT }}"
            echo "Branch: ${{ github.event.workflow_run.head_branch }}"

        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Setup jdk 21 for Pre-deploy Check
          uses: actions/setup-java@v4
          with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'
        
        - name: Authenticate to Google Cloud
          id: gcloud-auth
          uses: google-github-actions/auth@v2
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ vars.WIF_PROVIDER }}
            service_account: ${{ vars.APP_DEPLOYER_SERVICE_ACCOUNT }}

        - name: Pulumi Pre-Deploy Check (Preview)
          uses: pulumi/actions@v6
          with:
              command: preview
              stack-name: dev
              work-dir: ./pulumi-infra
          env:
              PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
              GCP_ACCESS_TOKEN: ${{ steps.gcloud-auth.outputs.access_token }}
              PULUMI_CONFIG_PASSTHROUGH: | 
                gcp:project=${{ vars.GCP_PROJECT_ID }},\
                gcp:region=${{ vars.GCP_REGION }},\
                azure-native:subscriptionId=${{ vars.AZURE_SUBSCRIPTION_ID }},\
                azure-native:location=${{ vars.AZURE_LOCATION }},\
                app-image=${{ inputs.image_uri }}